### ISSUE TITLE
"jspm install npm:three" bug

### ISSUE THREAD

**Issue by speigg** [jspm/npm#41] opened 2015-01-27 00:43 UTC
Unnecessarily adds Buffer and process as dependencies.

**Comment by guybedford** [comment] 2015-01-27 07:54
Thanks - ok we can improve this by detecting the use of Buffer or Process using proper scope analysis on the tree instead of regular expressions.

**Comment by guybedford** [comment] 2015-02-01 11:48
Let me know if this seems urgent, but for now I'm prioritising other issues first.

**Comment by speigg** [comment] 2015-02-01 13:48
That's fine, I can use github:mrdoob/three for now, but npm would be nice eventually as it just downloads the build files.

**Comment by guybedford** [comment] 2015-04-19 22:46
Duplicate of https://github.com/jspm/npm/issues/55.

**Closed by guybedford** 2015-04-19 22:46 UTC
