### ISSUE TITLE
Skipping node builtins

### ISSUE THREAD

**Issue by subesokun** [jspm/npm#77] opened 2015-06-03 15:09 UTC
I'm using a new library which depends on the [reflect-metadata](https://www.npmjs.com/package/reflect-metadata) npm package but as this package tries to require the node crypto library in case it's running in a node environment, the bundled file (via `jspm bundle`) becomes quite heavy. Normally when loading this library in the browser it will fallback to some very simple random byte generator instead of using the node crypto library. But when using jspm it thinks that it's running in a node environment and then requires the crypto library (see [here](https://github.com/rbuckton/ReflectDecorators/blob/1a07d3346d48ffbc77927c70245740debe09eb13/Reflect.js#L842)).

Normally this would be a good thing as via jspm this package can use also the stronger crypto library when running in a browser but this crypto library (+ dependencies) is really heavy and hence not really suitable for a web application.

Would it make sense to be able to tell jspm explicitly during installation that it shall skip including the node builtins to force npm packages to switch back into "browser" mode? Something like `jspm install --skip-node-builtins` or similar?

**Comment by guybedford** [comment] 2015-06-05 12:01
Interesting. I wonder if an override like `{ map: { 'crypto': '@empty' } }` could work here? I'd also be interested to know what Browserify do in this situation actually, as surely they must have the same issue for their users and have a solution for this already.

**Comment by subesokun** [comment] 2015-06-05 12:12
I see, yes that would be very interesting to see how Browserify solves that issue. In fact just excluding the crypto package won't help as this reflect-metadata package will still think that it runs in a Node environment and tries to load that package + fails (most likely). Somehow [this condition](https://github.com/rbuckton/ReflectDecorators/blob/1a07d3346d48ffbc77927c70245740debe09eb13/Reflect.js#L838) in their code has to be evaluated to false.

**Comment by guybedford** [comment] 2015-06-05 12:33
Ok that makes sense - I think you'll find that condition IS evaluating to false, the issue is that jspm is just downloading the dependency anyway despite it not being used.

In this case, `map: { 'crypto': '@empty' }` should exactly solve your issue.

**Comment by subesokun** [comment] 2015-06-05 12:47
Oh I see, thanks for the clarification. I've mixed some things up :( The install instructions would look like `jspm install npm:reflect-metadata -o "{ 'map': { 'crypto': '@empty' } }"` or? Somehow it's still downloading the crypto library (using jspm 0.15.6).

**Comment by guybedford** [comment] 2015-06-05 12:51
Right that will still download it, but it won't try and load it in the browser.

We definitely need to work out a better story here, just trying to see if we can get you a simple hack for now? Or are you more interested in working out the larger solution here?

**Comment by subesokun** [comment] 2015-06-05 12:59
Ah great, I've just tried to bundle it and it's getting properly excluded. I thought this map would also affect the download behavior but if it's not getting loaded during runtime or included in the bundle then that's already enough for me at this point. Though to save bandwidth it would be nice if the download can be skipped as well. I'll try now if this reflect-metadata package is still working as expected when the crypto library is being excluded.

**Comment by subesokun** [comment] 2015-06-05 13:25
Seems like it's still working as before :) Thanks for the tip! As I've a private jspm registry I could patch the override there but as you said already this is a simple hack which we can't push into the real registry. Would be keen to see how that can be solved in general :)

**Comment by guybedford** [comment] 2015-06-05 13:31
I think the empty mapping is the right thing to do, and allows one to selectively ignore builtins.

I've added support to not download for this case in https://github.com/jspm/npm/commit/fa4be763c19fa3819ed52b7c764934c4255ac511, let me know if that works for you.

**Comment by subesokun** [comment] 2015-06-05 14:07
Great, I'll test your fix but with the latest master the typescript plugin has some issues and throws an error. Have to look on that. Would this fix also prevent that these dependencies are getting listed in the `config.js`?

I was experimenting now with following override rule and it really removed all node builtin dependencies

```bash
jspm install -o "{ 'map': { 'process': '@empty', 'assert': '@empty', 'buffer': '@empty', 'child_process': '@empty', 'constants': '@empty', 'crypto': '@empty', 'events': '@empty', 'fs': '@empty', 'os': '@empty', 'path': '@empty', 'process': '@empty', 'readline': '@empty', 'stream': '@empty', 'url': '@empty', 'util': '@empty', 'vm': '@empty' } }"
```

Could such a command be wrapped in a handy `--skip-node-builtins` command? Also I had now the use case that I explicitly want to include only the path library, so something like `--skip-node-builtins * - path` would be awesome.

**Comment by guybedford** [comment] 2015-06-05 14:10
I think this sort of stuff should be implemented as part of automated override workflow wizards like the experiment in https://github.com/jspm/jspm-cli/pull/602. For now I don't there's a place for it in the main API yet though so would suggest sticking with the override approach.

**Comment by subesokun** [comment] 2015-06-05 14:37
Ok makes sense. Would it be possible to store this override rule in the package json so that it gets appended to every install call? Otherwise I'd need to add some shell script that calls jspm install with this override argument.

**Comment by guybedford** [comment] 2015-06-05 14:38
Yes overrides do get stored in the package.json.

**Comment by guybedford** [comment] 2015-06-06 09:31
I've added this into jspm core not to install things with map overrides https://github.com/jspm/jspm-cli/commit/70acf9c50a35dc117431aee3fa5debe10a772cb1. Will see how this goes as a workflow. Closing as I think this is the best option for now.

**Closed by guybedford** 2015-06-06 09:31 UTC

**Comment by subesokun** [comment] 2015-06-07 09:45
Thanks, I'll experiment around with these `@empty` overrides and see how it works out for me :)
